### PR TITLE
Various fixes and improvements

### PR DESCRIPTION
**Pull request by dpursehouse**
I haven't been able to verify that it all still works. I couldn't get the tests to run even with the environment variables (from the travis config) set.

### CODE REVIEW

**Comment by hayate** [comment]
thanks for the PR @dpursehouse we will try to fix the tests as soon as we have some time.

**Comment by dpursehouse** [comment]
@hayate I think it wasn't working for me before because of an internet problem on my side; it wasn't even connecting to the test server.  Now all the tests are passing - I don't see the error that was reported by Travis.

http://paste.openstack.org/show/476675/

**Comment by hayate** [comment]
LGTM

**Comment by seikoudoku2000** [comment]
LGTM.
As @dpursehouse mentioned, we should have some description about Java version. Maybe we can add in README.md?

**Comment by dpursehouse** [comment]
If you can hold off on merging this PR for a while, I'll add another commit tonight.

**Comment by dpursehouse** [comment]
@hayate @seikoudoku2000 I've updated the README as discussed earlier, and also added a couple more improvements.  PTAL.

**Comment by dpursehouse** [comment]
@hayate @seikoudoku2000 are there any more modifications needed before this can be merged?

**Comment by dpursehouse** [comment]
Closing this PR but leaving the branch on my fork.  If you want to take the fixes, you can reopen and merge it, or just cherry-pick specific ones (i.e. if you don't want the backward-incompatible Java 7 changes).

**Pull request closed without merging**
