### PR TITLE
[#93498368] Fix parameter name: gengo -> mygengo

### PR DESCRIPTION
**Pull request by narusemotoki**
Not `for_gengo`, `for_mygengo` is.

### CODE REVIEW

**Comment by ninotoshi** [comment]
Do you need to change this, too?
https://github.com/gengo/gengo-java/blob/4a6bce6a53ff41ea016b427de0b6baffcc53f095/src/main/java/com/gengo/client/payloads/Approval.java#L54

**Comment by narusemotoki** [comment]
@ninotoshi Good catch Thank you!

**Comment by yugui** [comment]
LGTM

**Comment by hayate** [comment]
:+1: LGTM

**Pull request merged**
